apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: tetragon-cluster-01
nodes:
- role: control-plane
  extraMounts:
      - hostPath: /tmp
        containerPath: /procHost
# - role: worker
#   extraMounts:
#       - hostPath: /tmp
#         containerPath: /procHost
# - role: worker
#   extraMounts:
#       - hostPath: /tmp
#         containerPath: /procHost
networking:
  disableDefaultCNI: true
  ipFamily: dual
  apiServerAddress: 127.0.0.1